# Generated by Django 6.0.6 on 2026-06-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
